---
apiVersion: "apps/v1beta2"
kind: Deployment
metadata:
  name: "lagom-devops-example-impl-v1-0-snapshot"
  labels:
    app: "lagom-devops-example-impl"
    appNameVersion: "lagom-devops-example-impl-v1-0-snapshot"
    "akka.lightbend.com/service-name": "lagom-devops-example-impl"
spec:
  replicas: 2
  selector:
    matchLabels:
      appNameVersion: "lagom-devops-example-impl-v1-0-snapshot"
  template:
    metadata:
      labels:
        app: "lagom-devops-example-impl"
        appNameVersion: "lagom-devops-example-impl-v1-0-snapshot"
        "akka.lightbend.com/service-name": "lagom-devops-example-impl"
    spec:
      restartPolicy: Always
      containers:
        - name: "lagom-devops-example-impl"
          image: "lagom-devops-example-impl:1.0-SNAPSHOT"
          imagePullPolicy: IfNotPresent
          env:
            - name: "CASSANDRA_CLUSTER"
              value: "cassandra.namespace:9042"
            - name: "KAFKA_CLUSTER"
              value: "kafka.namespace:9092"
            - name: "RP_APP_NAME"
              value: "lagom-devops-example-impl"
            - name: "RP_APP_TYPE"
              value: lagom
            - name: "RP_APP_VERSION"
              value: "1.0-SNAPSHOT"
            - name: "RP_DYN_JAVA_OPTS"
              value: "-Dakka.discovery.kubernetes-api.pod-namespace=$RP_NAMESPACE"
            - name: "RP_JAVA_OPTS"
              value: "-Dplay.server.pidfile.path=/dev/null -Dconfig.resource=rp-application.conf -Dakka.management.cluster.bootstrap.contact-point-discovery.discovery-method=kubernetes-api -Dakka.management.cluster.bootstrap.contact-point-discovery.port-name=management -Dakka.management.cluster.bootstrap.contact-point-discovery.effective-name=lagom-devops-example-impl -Dakka.discovery.kubernetes-api.pod-label-selector=akka.lightbend.com/service-name=%s -Dakka.management.cluster.bootstrap.contact-point-discovery.required-contact-point-nr=2"
            - name: "RP_KUBERNETES_POD_IP"
              valueFrom:
                fieldRef:
                  fieldPath: "status.podIP"
            - name: "RP_KUBERNETES_POD_NAME"
              valueFrom:
                fieldRef:
                  fieldPath: "metadata.name"
            - name: "RP_MODULES"
              value: "akka-cluster-bootstrapping,akka-management,common,service-discovery,status"
            - name: "RP_NAMESPACE"
              valueFrom:
                fieldRef:
                  fieldPath: "metadata.namespace"
            - name: "RP_PLATFORM"
              value: kubernetes
          ports:
            - containerPort: 9000
              name: http
            - containerPort: 2552
              name: remoting
            - containerPort: 8558
              name: management
          volumeMounts: []
          command:
            - "/opt/docker/bin/rp-start"
          args:
            - "bin/lagom-devops-example-impl"
          readinessProbe:
            httpGet:
              path: "/platform-tooling/ready"
              port: management
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: "/platform-tooling/healthy"
              port: management
            periodSeconds: 10
            initialDelaySeconds: 60
      volumes: []
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: "lagom-devops-example-impl"
  name: "lagom-devops-example-impl"
spec:
  ports:
    - name: http
      port: 9000
      protocol: TCP
      targetPort: 9000
    - name: remoting
      port: 2552
      protocol: TCP
      targetPort: 2552
    - name: management
      port: 8558
      protocol: TCP
      targetPort: 8558
  selector:
    app: "lagom-devops-example-impl"
